name: Metrics
on:
  # Schedule updates (e.g., every morning)
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual runs from the Actions tab
  workflow_dispatch:
  # Run on push to main/master
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
  # Use ubuntu-latest for the runner
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to commit the generated SVG back to the repo
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your generated token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: YOUR_USERNAME
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
